### ISSUE TITLE
Can't open the plugin

### ISSUE THREAD

**Issue by Dolomich** [Battelle/cantordust#5]
After adding the plugin in the script manager and trying to open it I seem to always get that error :

```
Error running script: Cantordust.java
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Dolo/Downloads/images/dbf5s3hi0ky11.jpg
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Dolo/Downloads/images/dbf5s3hi0ky11.jpg
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at Cantordust.getJavaData(Cantordust.java:114)
	at Cantordust.getData(Cantordust.java:71)
	at Cantordust.run(Cantordust.java:50)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:365)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:220)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:198)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:57)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2020-Feb-12 1149 EST
Ghidra Version: 9.1.2
Java Home: C:\Program Files\Java\jdk-11.0.9
JVM Version: Oracle Corporation 11.0.9
OS: Windows 7 6.1 amd64
```

I have some files open in Ghidra, I tried running it in administrator mode, I even tried different JDK versions but I keep getting it.

Clearly this seems path related, but I'm not sure what to do about it.

**Comment by Dolomich** [comment]
I tried using Ghidra v9.1, same error
```
Error running script: Cantordust.java
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Dolo/Desktop/DF_divination_2.jpg
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Dolo/Desktop/DF_divination_2.jpg
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at Cantordust.getJavaData(Cantordust.java:114)
	at Cantordust.getData(Cantordust.java:71)
	at Cantordust.run(Cantordust.java:50)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:365)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:220)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:198)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:57)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

---------------------------------------------------
Build Date: 2019-Oct-23 1737 EDT
Ghidra Version: 9.1
Java Home: C:\Program Files\Java\jdk-15.0.1
JVM Version: Oracle Corporation 15.0.1
OS: Windows 7 6.1 amd64
```


I also tried using v9.2, still don't start but different error

```
GhidraProvider
java.lang.NoClassDefFoundError: GhidraProvider
	at Cantordust.writeBinLocation(Cantordust.java:127)
	at Cantordust.run(Cantordust.java:48)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:379)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:234)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:212)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

---------------------------------------------------
Build Date: 2020-Nov-13 1112 EST
Ghidra Version: 9.2
Java Home: C:\Program Files\Java\jdk-15.0.1
JVM Version: Oracle Corporation 15.0.1
OS: Windows 7 6.1 amd64
```

**Comment by sengi12** [comment]
Thanks for bringing this to our attention @Dolomich! As far as I see there are two different issues here. 

**Issue 1 (v9.1):** 
There is a Ghidra function that Cantordust relies on to get the bytes from the file: `currentProgram.getExecutablePath();`
When this function runs in Linux, it outputs a full path to the file as expected. However in Windows, it outputs the full path with an extra `/` at the beginning. Notice how the error occurs with this path: `/C:/Users/Dolo/Desktop/DF_divination_2.jpg`. 

Our current work around is to simply check if the OS is Windows 10, and if so remove the extra `/`. (See `Cantordust.java: line 111`) However your test was done using Windows 7, which is not checked for as Windows 7 technically reached its EOL as of [January 14th, 2020](https://www.microsoft.com/en-us/microsoft-365/windows/end-of-windows-7-support). 

A simple work around for your case would be to change `Cantordust.java: line 111`, so that it removes the extra `/` for Windows 7 too. Let me know, but that should work!

**Issue 2 (v9.2):**
After some investigation, it appears that the NSA's newest release of Ghidra (9.2) has a changed how it compiles plugins. In its current state, Cantordust is not compatible with v9.2 sadly. I'll look into this over the next few days and see if I can get it working again.

I hope this was helpful! Please let me know if run into any other problems :slightly_smiling_face:

**Comment by Dolomich** [comment]
Thanks for you answer, I managed to get the plugin working

**Comment by sengi12** [comment]
#20 should fix both halves of this.

**v9.1 `InvalidPathException`** — as noted above the check was `os.name.equals("Windows 10")`, so @Dolomich's Windows 7 fell through. #20 matches any Windows release rather than adding another exact-version check, requires a drive letter so UNC paths aren't corrupted, and guards a null or empty path. It also catches the exception: `InvalidPathException` is unchecked, so it escaped `getData()` and aborted the script instead of falling back to Ghidra's byte source — which is why this reads as "can't open the plugin" rather than a bad-path warning.

**v9.2 `NoClassDefFoundError: GhidraProvider`** — already resolved. `writeBinLocation()` and `GhidraProvider` were removed in 66e40cd when #6 merged, and neither exists on current master.

There's likely a third path to this same symptom, now also fixed: `MainInterface` derived an address with `Long.parseLong(getMinAddress().toString(false), 16)` during construction, which throws on segmented addresses (`"1000:0000"`) and on 64-bit addresses above `Long.MAX_VALUE`. When that throws, the window never opens.
